---
- hosts: myserver
  become: yes
  become_method: sudo
  tasks:
    - name: ensure Java is installed
      apt:
        name: default-jre
        state: present
        update_cache: yes
    - name: create application directory
      file:
        path: /var/application
        state: directory
    - name: copy application
      copy:
        src: app.jar
        dest: /var/application/app.jar
    - name: copy starting script
      copy:
        src: hello.sh
        dest: /var/application/hello.sh
        mode: a+x
    - name: configure hello as a service
      file:
        path: /etc/init.d/hello
        state: link
        force: yes
        src: /var/application/hello.sh
    - name: run application service
      service:
        name: hello
        enabled: true
        state: started
    
